//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DataDictionary", typeof(DataDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Settings.
        /// </summary>
        public static string AdminSettings {
            get {
                return ResourceManager.GetString("AdminSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aien Co..
        /// </summary>
        public static string AienCo {
            get {
                return ResourceManager.GetString("AienCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Domain.
        /// </summary>
        public static string ApplicationDomain {
            get {
                return ResourceManager.GetString("ApplicationDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is Active.
        /// </summary>
        public static string ApplicationIsActive {
            get {
                return ResourceManager.GetString("ApplicationIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Role.
        /// </summary>
        public static string ApplicationRole {
            get {
                return ResourceManager.GetString("ApplicationRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Roles.
        /// </summary>
        public static string ApplicationRoles {
            get {
                return ResourceManager.GetString("ApplicationRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Secret.
        /// </summary>
        public static string ApplicationSecret {
            get {
                return ResourceManager.GetString("ApplicationSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Secrets.
        /// </summary>
        public static string ApplicationSecrets {
            get {
                return ResourceManager.GetString("ApplicationSecrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Title.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Url.
        /// </summary>
        public static string ApplicationUrl {
            get {
                return ResourceManager.GetString("ApplicationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Urls.
        /// </summary>
        public static string ApplicationUrls {
            get {
                return ResourceManager.GetString("ApplicationUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Time.
        /// </summary>
        public static string AssignDateTime {
            get {
                return ResourceManager.GetString("AssignDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black IP.
        /// </summary>
        public static string BlackIP {
            get {
                return ResourceManager.GetString("BlackIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black IPs.
        /// </summary>
        public static string BlackIPs {
            get {
                return ResourceManager.GetString("BlackIPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked IPs.
        /// </summary>
        public static string BlockedIPs {
            get {
                return ResourceManager.GetString("BlockedIPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Phone Number.
        /// </summary>
        public static string CellPhoneNumber {
            get {
                return ResourceManager.GetString("CellPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Phone Number Verification Key.
        /// </summary>
        public static string CellPhoneNumberVerificationKey {
            get {
                return ResourceManager.GetString("CellPhoneNumberVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Token Per Request.
        /// </summary>
        public static string CheckTokenPerRequest {
            get {
                return ResourceManager.GetString("CheckTokenPerRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©2021.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Count.
        /// </summary>
        public static string CountryCount {
            get {
                return ResourceManager.GetString("CountryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Iran and Systemic IPs.
        /// </summary>
        public static string DeleteIranAndSystemicIPs {
            get {
                return ResourceManager.GetString("DeleteIranAndSystemicIPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Profile.
        /// </summary>
        public static string DisplayProfile {
            get {
                return ResourceManager.GetString("DisplayProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Public Profile.
        /// </summary>
        public static string DisplayPublicProfile {
            get {
                return ResourceManager.GetString("DisplayPublicProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs.
        /// </summary>
        public static string Docs {
            get {
                return ResourceManager.GetString("Docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Name.
        /// </summary>
        public static string DomainName {
            get {
                return ResourceManager.GetString("DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address Verification Key.
        /// </summary>
        public static string EmailAddressVerificationKey {
            get {
                return ResourceManager.GetString("EmailAddressVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Request Time.
        /// </summary>
        public static string FirstRequestDateTime {
            get {
                return ResourceManager.GetString("FirstRequestDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From IP.
        /// </summary>
        public static string FromIP {
            get {
                return ResourceManager.GetString("FromIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From IP Number.
        /// </summary>
        public static string FromIPNumber {
            get {
                return ResourceManager.GetString("FromIPNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get And Insert Iran IPs.
        /// </summary>
        public static string GetAndInsertIranIPs {
            get {
                return ResourceManager.GetString("GetAndInsertIranIPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get IP Locations.
        /// </summary>
        public static string GetIpLocations {
            get {
                return ResourceManager.GetString("GetIpLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Url.
        /// </summary>
        public static string ImageUrl {
            get {
                return ResourceManager.GetString("ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Date Time.
        /// </summary>
        public static string InsertDateTime {
            get {
                return ResourceManager.GetString("InsertDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Count.
        /// </summary>
        public static string IPCount {
            get {
                return ResourceManager.GetString("IPCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Number.
        /// </summary>
        public static string IPNumber {
            get {
                return ResourceManager.GetString("IPNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Phone Number is Verified.
        /// </summary>
        public static string IsCellPhoneNumberVerified {
            get {
                return ResourceManager.GetString("IsCellPhoneNumberVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletable.
        /// </summary>
        public static string IsDeletable {
            get {
                return ResourceManager.GetString("IsDeletable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address Verified.
        /// </summary>
        public static string IsEmailAddressVerified {
            get {
                return ResourceManager.GetString("IsEmailAddressVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Restricted.
        /// </summary>
        public static string IsIpRestricted {
            get {
                return ResourceManager.GetString("IsIpRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Code is Verified.
        /// </summary>
        public static string IsNationalCodeVerified {
            get {
                return ResourceManager.GetString("IsNationalCodeVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Verified.
        /// </summary>
        public static string IsNotVerified {
            get {
                return ResourceManager.GetString("IsNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string IsOwner {
            get {
                return ResourceManager.GetString("IsOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile is Public.
        /// </summary>
        public static string IsProfilePublic {
            get {
                return ResourceManager.GetString("IsProfilePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systemic.
        /// </summary>
        public static string IsSystemic {
            get {
                return ResourceManager.GetString("IsSystemic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updatable.
        /// </summary>
        public static string IsUpdatable {
            get {
                return ResourceManager.GetString("IsUpdatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string IsVerified {
            get {
                return ResourceManager.GetString("IsVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Request Time.
        /// </summary>
        public static string LastRequestDateTime {
            get {
                return ResourceManager.GetString("LastRequestDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of.
        /// </summary>
        public static string ListOf {
            get {
                return ResourceManager.GetString("ListOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginToSite {
            get {
                return ResourceManager.GetString("LoginToSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Count.
        /// </summary>
        public static string MemberCount {
            get {
                return ResourceManager.GetString("MemberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        public static string Membership {
            get {
                return ResourceManager.GetString("Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Time.
        /// </summary>
        public static string MembershipDateTime {
            get {
                return ResourceManager.GetString("MembershipDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memberships.
        /// </summary>
        public static string Memberships {
            get {
                return ResourceManager.GetString("Memberships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Applications.
        /// </summary>
        public static string MyApplications {
            get {
                return ResourceManager.GetString("MyApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Memberships.
        /// </summary>
        public static string MyMemberships {
            get {
                return ResourceManager.GetString("MyMemberships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Code.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Description.
        /// </summary>
        public static string OwnerDescription {
            get {
                return ResourceManager.GetString("OwnerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile is not public.
        /// </summary>
        public static string ProfileIsNotPublic {
            get {
                return ResourceManager.GetString("ProfileIsNotPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile is public.
        /// </summary>
        public static string ProfileIsPublic {
            get {
                return ResourceManager.GetString("ProfileIsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterToSite {
            get {
                return ResourceManager.GetString("RegisterToSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Count.
        /// </summary>
        public static string RequestCount {
            get {
                return ResourceManager.GetString("RequestCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Url.
        /// </summary>
        public static string ReturnUrl {
            get {
                return ResourceManager.GetString("ReturnUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Count.
        /// </summary>
        public static string RoleCount {
            get {
                return ResourceManager.GetString("RoleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is Active.
        /// </summary>
        public static string RoleIsActive {
            get {
                return ResourceManager.GetString("RoleIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret.
        /// </summary>
        public static string Secret {
            get {
                return ResourceManager.GetString("Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secrets.
        /// </summary>
        public static string Secrets {
            get {
                return ResourceManager.GetString("Secrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Secured Page].
        /// </summary>
        public static string SecuredPage {
            get {
                return ResourceManager.GetString("SecuredPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Again Email Address Verification Key.
        /// </summary>
        public static string SendAgainEmailAddressVerificationKey {
            get {
                return ResourceManager.GetString("SendAgainEmailAddressVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL Required.
        /// </summary>
        public static string SslRequired {
            get {
                return ResourceManager.GetString("SslRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Secured Page!.
        /// </summary>
        public static string ThisIsASecuredPage {
            get {
                return ResourceManager.GetString("ThisIsASecuredPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title in Arabic.
        /// </summary>
        public static string TitleInArabic {
            get {
                return ResourceManager.GetString("TitleInArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title in English.
        /// </summary>
        public static string TitleInEnglish {
            get {
                return ResourceManager.GetString("TitleInEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title in Farsi.
        /// </summary>
        public static string TitleInFarsi {
            get {
                return ResourceManager.GetString("TitleInFarsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To IP.
        /// </summary>
        public static string ToIP {
            get {
                return ResourceManager.GetString("ToIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To IP Number.
        /// </summary>
        public static string ToIPNumber {
            get {
                return ResourceManager.GetString("ToIPNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Request Count.
        /// </summary>
        public static string TotalRequestCount {
            get {
                return ResourceManager.GetString("TotalRequestCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date Time.
        /// </summary>
        public static string UpdateDateTime {
            get {
                return ResourceManager.GetString("UpdateDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile.
        /// </summary>
        public static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Avatar.
        /// </summary>
        public static string UploadAvatar {
            get {
                return ResourceManager.GetString("UploadAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urls.
        /// </summary>
        public static string Urls {
            get {
                return ResourceManager.GetString("Urls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Activity.
        /// </summary>
        public static string UserActivity {
            get {
                return ResourceManager.GetString("UserActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Activity Logs.
        /// </summary>
        public static string UserActivityLogs {
            get {
                return ResourceManager.GetString("UserActivityLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Count.
        /// </summary>
        public static string UserCount {
            get {
                return ResourceManager.GetString("UserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Activity Logs.
        /// </summary>
        public static string UsersActivityLogs {
            get {
                return ResourceManager.GetString("UsersActivityLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        public static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify User Email Address.
        /// </summary>
        public static string VerifyUserEmailAddress {
            get {
                return ResourceManager.GetString("VerifyUserEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 5.4.9.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White IPs.
        /// </summary>
        public static string WhiteIPs {
            get {
                return ResourceManager.GetString("WhiteIPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeus Owner Description.
        /// </summary>
        public static string ZeusOwnerDescription {
            get {
                return ResourceManager.GetString("ZeusOwnerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeus System.
        /// </summary>
        public static string ZeusSystem {
            get {
                return ResourceManager.GetString("ZeusSystem", resourceCulture);
            }
        }
    }
}
